#!groovy

@Library('jenkins-library') _

def projectName = "valheim-server"

def LABEL = containerTemplates.nodeLabel(projectName)

def buildImages = ['docker']

def containers =  containerTemplates.build(this, buildImages)

podTemplate(
    label: LABEL,
    containers: containers,
    //volumes: volumes,
    serviceAccount: 'jenkins',
    yaml: '''
    spec:
      securityContext:
        fsGroup: 1000
    ''') {
        timeout(time:10, unit: 'MINUTES') {
            node(LABEL) {
              
                checkout scm
                entrypoint()
            }
        }
}
